# Generated by Django 4.1.7 on 2023-04-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat11', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bye',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='college',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='legbye',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='noball',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wide',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
    ]
