# Generated by Django 4.1.7 on 2023-04-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stat11', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bye',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='college',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='legbye',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='noball',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wide',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='bowled_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowled_out_by', to='stat11.player'),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batterscoreboard',
            name='wicket_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_taker', to='stat11.player'),
        ),
        migrations.AlterField(
            model_name='bowlerscoreboard',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowlerscoreboard',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlerscoreboard',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlerscoreboard',
            name='maidens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowlerscoreboard',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowlerscoreboard',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
    ]
