# Generated by Django 4.1.7 on 2023-04-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat11', '0005_alter_batterscoreboard_bowled_out_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bye',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='college',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='legbye',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='noball',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wide',
            field=models.IntegerField(default=0),
        ),
    ]
